# sass-lint configuration
options:
  merge-default-rules: false
  max-warnings: 50
files:
  include: 'resources/assets/sass/**/*.s+(a|c)ss'
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 1
  no-debug: 1
#  no-ids: 2
  no-important: 2
  # 「Google HTML/CSS Style Guide」の小文字推奨にする。
  # ※hex-notation の デフォルトは lowercase
  hex-notation: 2
  indentation:
    - 2
    -
      size: 2
  property-sort-order:
    - 1
    -
      order:
        - display
        - margin
      ignore-custom-properties: true
